name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            bin_path: ./build/stockprice
          - os: macOS-latest
            bin_path: ./build/stockprice
          - os: windows-latest
            bin_path: ./build/Release/stockprice.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Check libcurl version
        run: curl-config --version
      - name: pre-build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: |
          cd build
          cmake --build . --config Release
      - name: test
        run: |
          ${{ matrix.bin_path }}