name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
        include:
          - os: macOS-latest
            bin_path: ./build/stockprice
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: build 
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: test
        run: |
          ${{ matrix.bin_path }}