name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
        include:
          # - os: ubuntu-latest
          #   bin_path: ./build/stockprice
          - os: macOS-latest
            bin_path: ./build/stockprice
          # - os: windows-latest
          #   bin_path: ./build/Release/stockprice.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: build OpenSSL
        run: |
          cd openssl-3.2.1
          ./Configure no-shared no-zlib enable-rc5 darwin64-x86_64-cc
          make
      - name: build Stockprice
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: test
        run: |
          ${{ matrix.bin_path }}