name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-unix:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: pre-build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: |
          cd build
          cmake --build .
      - name: test
        run: |
          cd build
          ./stockprice
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: pre-build
        run: |
          mkdir build
          cd build
          cmake ..
      - name: build
        run: |
          cd build
          cmake --build . --config Release
      - name: List directory contents
        run: |
          cd build
          ls
      - name: List debug contents
        run: |
          cd build
          cd Debug
          ls
      - name: List stockprice.dir contents
        run: |
          cd build
          cd stockprice.dir
          ls
      - name: test
        run: |
          cd build
          stockprice.exe